### ISSUE TITLE
Errno::ENOENT: No such file or directory @ realpath_rec - /home/git/repositories

### ISSUE THREAD

**Issue by kjm0001** [sbadia/puppet-gitlab#245]
Issues with 8-12 stable version:
Debug: Exec[install gitlab](provider=posix): Executing 'bundle install -j1 --without development aws test postgres --deployment'
Debug: Executing with uid=git: 'bundle install -j1 --without development aws test postgres --deployment'
Notice: /Stage[main]/Gitlab::Install/Exec[install gitlab]/returns: executed successfully
Info: /Stage[main]/Gitlab::Install/Exec[install gitlab]: Scheduling refresh of Exec[run migrations]
Debug: /Stage[main]/Gitlab::Install/Exec[install gitlab]: The container Class[Gitlab::Install] will propagate my refresh event
Debug: Exec[setup gitlab database](provider=posix): Executing '/usr/bin/yes yes | bundle exec rake gitlab:setup RAILS_ENV=production'
Debug: Executing with uid=git: '/usr/bin/yes yes | bundle exec rake gitlab:setup RAILS_ENV=production'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: rake aborted!
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: Errno::ENOENT: No such file or directory @ realpath_rec - /home/git/repositories
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/config/initializers/6_validations.rb:6:in `realpath'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/config/initializers/6_validations.rb:6:in`realpath'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/config/initializers/6_validations.rb:6:in `find_parent_path'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/config/initializers/6_validations.rb:22:in`block in validate_storages'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/config/initializers/6_validations.rb:19:in `each'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/config/initializers/6_validations.rb:19:in`validate_storages'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/config/initializers/6_validations.rb:29:in `<top (required)>'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in`load'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in`load_dependency'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in`block in load_config_initializer'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in`load_config_initializer'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in`each'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in`instance_exec'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in`block in run_initializers'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in`tsort_each_child'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in`initialize!'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/config/environment.rb:5:in `<top (required)>'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in`require'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in`load_dependency'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in`require_environment!'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /usr/local/bin/bundle:23:in`load'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: /usr/local/bin/bundle:23:in `<main>'
Notice: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: Tasks: TOP => gitlab:setup => environment
Error: /usr/bin/yes yes | bundle exec rake gitlab:setup RAILS_ENV=production returned 1 instead of one of [0]
Error: /Stage[main]/Gitlab::Install/Exec[setup gitlab database]/returns: change from notrun to 0 failed: /usr/bin/yes yes | bundle exec rake gitlab:setup RAILS_ENV=production returned 1 instead of one of [0]

I was able to test with 8-6-stable and had no issues but when trying to use 8-12 stable version, errors out on the missing /home/git/repositories

**Comment by kjm0001** [comment]
After reviewing the differences between 8-6 and 8-12, looks like gitlab changed the code in the /home/git/gitlab-shell/bin/install file. 
8-6:
config = GitlabConfig.new
key_dir = File.dirname("#{config.auth_file}")

commands = [
  %W(mkdir -p #{config.repos_path}),
  %W(mkdir -p #{key_dir}),
  %W(chmod 700 #{key_dir}),
  %W(touch #{config.auth_file}),
  %W(chmod 600 #{config.auth_file}),
  %W(chmod ug+rwX,o-rwx #{config.repos_path}),
]
when executing at command line the directory is executed which works in the puppet module: 
ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-linux]
-bash-4.1$ ruby install
mkdir -p /home/git/repositories: OK
mkdir -p /home/git/.ssh: OK
chmod 700 /home/git/.ssh: OK
touch /home/git/.ssh/authorized_keys: OK
chmod 600 /home/git/.ssh/authorized_keys: OK
chmod ug+rwX,o-rwx /home/git/repositories: OK

in 8-12:
config = GitlabConfig.new
key_dir = File.dirname("#{config.auth_file}")
**repository_storage_paths = ARGV**

commands = [
  %W(mkdir -p #{key_dir}),
  %W(chmod 700 #{key_dir}),
]

repository_storage_paths.each do |repository_storage_path|
  commands << %W(mkdir -p #{repository_storage_path})
  commands << %W(chmod ug+rwX,o-rwx #{repository_storage_path})
end

when executing at commandline:
-bash-4.1$ ruby gitlab-shell/bin/install
mkdir -p /home/git/.ssh: OK
chmod 700 /home/git/.ssh: OK

the repositories directory is not created, as it looks it is an argument now
so then the puppet module fails when executing bundle install -j1 --without development aws test postgres --deployment since no the repositories directory was not created
